apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph-mysql-deployment
  namespace: ceph
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph-mysql-deployment
  template:
    metadata:
      labels:
        app: ceph-mysql-deployment
    spec:
      nodeName: hadoop02
      containers:                                                            # Pod里容器的定义部分
        - name: ceph-mysql-deployment                                                      # 容器的名称
          image: registry.cn-hangzhou.aliyuncs.com/chinapex/mysql:5.7.24            # 容器对应的docker镜像
          volumeMounts:                                                   # 容器内挂载点的定义部分
            - name: time-zone                                             # 容器内挂载点名称
              mountPath: /etc/localtime                                # 容器内挂载点路径，可以是文件或目录
            - name: mysql-data
              mountPath: /var/lib/mysql                                  # 容器内mysql的数据目录
          ports:
            - containerPort: 3306                                           # 容器暴露的端口号
          env:                                                                        # 写入到容器内的环境容量
            - name: MYSQL_ROOT_PASSWORD                  # 定义了一个mysql的root密码的变量
              value: "adamlv159@#"
      volumes:                                                                      # 本地需要挂载到容器里的数据卷定义部分
        - name: time-zone                                                   # 数据卷名称，需要与容器内挂载点名称一致
          hostPath:
            path: /etc/localtime                       # 将localtime文件挂载到容器里，可让容器使用本地的时区
        - name: mysql-data
          persistentVolumeClaim:
            claimName: ceph-mysql-pvc                      # 本地存放mysql数据的目录
   

---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mysql-svc
  namespace: ceph
  labels:
    name: ceph-mysql-svc
spec:
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: http
    nodePort: 30336
  selector:
    app: ceph-mysql-deployment
